### PR TITLE
Use ebu library for EPWING dictionaries

### PR DESCRIPTION
**Pull request by data-man**
I've tested some dicts with ebu-4.5 library from http://green.ribbon.to/~ikazuhiro/dic/files.
Windows libs should be compiled separately.

### CODE REVIEW

**Comment by nonwill** [comment]
I have switched to libebu since [last March](https://nonwill.github.io/post/goldendict/#2020317-2a0a%E4%BD%BF%E7%94%A8ebu%E4%BB%A3%E6%9B%BFeb%E5%A4%84%E7%90%86epwing%E6%A0%BC%E5%BC%8F%E5%AD%97%E5%85%B8%E5%A2%9E%E5%8A%A0basshttpswwwun4seencombasshtml%E5%8F%91%E9%9F%B3%E5%BC%95%E6%93%8E%E8%A7%A3%E5%86%B3%E7%A8%8B%E5%BA%8F%E9%80%80%E5%87%BA%E6%97%B6%E7%9A%84%E5%BC%82%E5%B8%B8%E9%97%AE%E9%A2%98%E8%A1%A8%E7%8E%B0%E4%B8%BA%E5%9C%A8%E9%83%A8%E5%88%86%E6%9C%BA%E5%99%A8%E4%B8%8A%E7%A8%8B%E5%BA%8F%E9%80%80%E5%87%BA%E5%90%8E%E4%B8%8D%E8%83%BD%E9%A9%AC%E4%B8%8A%E5%86%8D%E6%AC%A1%E5%90%AF%E5%8A%A8%E5%8F%AF%E8%83%BD%E9%9C%80%E8%A6%81%E7%AD%89%E5%BE%85%E8%BE%83%E9%95%BF%E6%97%B6%E9%97%B4%E6%88%96%E9%87%8D%E5%90%AF%E7%94%B5%E8%84%91%E5%90%8E%E6%89%8D%E8%83%BD%E5%90%AF%E5%8A%A8%E8%A7%A3%E5%86%B3%E5%88%92%E5%8F%96ocr%E5%88%B0%E7%9A%84%E5%AD%97%E7%AC%A6%E4%B8%B2%E4%BB%85%E6%9C%89%E6%97%A0%E6%95%88%E5%AD%97%E7%AC%A6%E6%A0%87%E7%82%B9%E7%AC%A6%E5%8F%B7%E7%AD%89%E6%97%B6%E7%A8%8B%E5%BA%8F%E5%BC%82%E5%B8%B8%E9%80%80%E5%87%BA%E7%9A%84%E9%97%AE%E9%A2%98%E8%A7%A3%E5%86%B3%E5%88%92%E8%AF%8D%E6%97%B6%E9%80%89%E5%8F%96%E5%8C%BA%E5%9F%9F%E4%B8%BA%E7%A9%BA%E6%97%A0%E5%AD%97%E7%AC%A6%E6%97%B6%E7%A8%8B%E5%BA%8F%E5%BC%82%E5%B8%B8%E9%80%80%E5%87%BA%E7%9A%84%E9%97%AE%E9%A2%98%E5%88%92%E8%AF%8D%E6%94%AF%E6%8C%81%E5%A4%9A%E5%9B%BD%E5%AE%B6%E5%9C%B0%E5%8C%BA%E8%AF%AD%E8%A8%80%E7%9A%84%E9%80%89%E9%85%8D), it goes well. EB_Hook should also be added to handle EB_HOOK_UNICODE, but seems nowhere to get such an epwing dictionary to test it.

**Comment by xiaoyifang** [comment]
I think the great difficulty here is most linux distributions or macos does not provide eb/ebu precompiled library.

**Comment by xiaoyifang** [comment]
how to compile libebu on windows? I have not succeed in compile it.

**Comment by vedgy** [comment]
A comment under https://github.com/mvf/qolibri/pull/38 suggests that *libebu* is not much better than *libeb*. Why should it replace *libeb* in GoldenDict? Perhaps just add optional support for building against *libebu* in _epwing_book.*_ and _goldendict.pro_, without touching bundled *libeb* in maclibs and winlibs?

**Comment by data-man** [comment]
Sorry? I don't use GD anymore.

**Comment by nonwill** [comment]
> Perhaps just add optional support for building against _libebu_ in _epwing_book.*_ and _goldendict.pro_, without touching bundled _libeb_ in maclibs and winlibs?

There is no difficulty in porting to libebu, only the name of C header files/lib should be changed in the GD source/pro files. I have been using libebu for several years, but don't feel any discomfort, and also users of GD++ did not report any problems about libebu. The biggest issue is that libebu is a private project with no public VCS repo and also without CI based builds.

**Comment by vedgy** [comment]
What are the advantages of libebu over libeb?

**Comment by nonwill** [comment]
The big advantage is that it has built-in support for utf8 encoding of EPWING content(but now few EPWING dictionaries were built with utf8 encoding).

**Comment by vedgy** [comment]
Interestingly, there are 28 votes for *libeb* and 0 votes for *ebu* in [AUR](https://aur.archlinux.org/packages?O=0&SeB=nd&K=epwing&outdated=&SB=p&SO=d&PP=50&submit=Go). This is probably because several AUR packages depend on *libeb* but none on *ebu*. Given such lack of clarity, the start should be optional, off-by-default libebu support. Judging by the changes in this PR, such optional support should be easy to implement.

**Comment by vedgy** [comment]
> > Given such lack of clarity, the start should be optional, off-by-default libebu support
> 
> Totally agree with it. 

Created #1635 that implements this idea.

**Pull request closed without merging**
