### PR TITLE
Generate and upload AppImage, closes #905

### LINKED ISSUE #905: AppImage package (as Early Access Builds for Linux Portable)
Propose setup `master` branch to produce autobuilds using Travis CI in AppImage format
* http://github.com/AppImage/AppImageKit
  * https://github.com/probonopd/linuxdeployqt

`.AppImage` is universal portable package format for most of Linux distributions, so it could be used for continiouse providing it as "Early Access Builds for Linux Portable"
* https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Linux-Portable

@probonopd, please, help GolenDict Team do solve this task! ;-)

P.S.: Strange, that this not yet requested earlier...
* https://github.com/AppImage/AppImageKit/wiki/AppImages

### PR DESCRIPTION
**Pull request by probonopd**
This PR, when merged, will compile this application on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload an [AppImage](http://appimage.org/) to your GitHub Releases page.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter
- No repositories needed. Suitable/optimized for air-gapped (offline) machines

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

__PLEASE NOTE:__ For this to work, you need to enable Travis CI for your repository as [described here](https://travis-ci.org/getting_started) __prior to merging this__, if you haven't already done so. Also, You need to set up `GITHUB_TOKEN` in Travis CI for this to work; please see https://github.com/probonopd/uploadtool.
If you would like to see only one entry for the Pull Request in your project's history, then please enable [this GitHub functionality](https://help.github.com/articles/configuring-commit-squashing-for-pull-requests/) on your repo. It allows you to squash (combine) the commits when merging.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

### CODE REVIEW

**Comment by probonopd** [comment]
An example AppImage can be downloaded from https://github.com/probonopd/goldendict/releases

**Comment by probonopd** [comment]
This has been wanted for six(!) years:
http://goldendict.org/forum/viewtopic.php?f=4&t=1764&p=7645#p7645

**Comment by Symbian9** [comment]
Why this pull not merged yet, @goldendict?

**Comment by HannanAkbar** [comment]
Please merge this PR. Anyone?

**Comment by HannanAkbar** [comment]
Closes #905

**Comment by Symbian9** [comment]
Dear, @goldendict devs, please, merge this pull!

**Comment by Symbian9** [comment]
Finish one more step, please:

> Also, You need to set up `GITHUB_TOKEN` in Travis CI for this to work; please see:
>
> - https://github.com/probonopd/uploadtool

**Comment by probonopd** [comment]
Thanks for merging. That extra step is needed for the builds to start appearing on https://github.com/goldendict/goldendict/releases. Thanks.

**Comment by Abs62** [comment]
Look in https://github.com/Abs62/goldendict/releases

**Comment by probonopd** [comment]
Yes, we need it in https://github.com/goldendict/goldendict/releases.

**Comment by Abs62** [comment]
I haven't access to "goldendict" account. Ask program author.

**Comment by probonopd** [comment]
Now I am puzzled, I was under the impression that you are the main contributor here? Who can help?

**Comment by Abs62** [comment]
[Konstantin Isakov](https://github.com/dragonroot) - GD author.

**Comment by Symbian9** [comment]
> Konstantin Isakov - GD author

Does he still active on GitHub? Maybe, there are other GD members with owners rights to this repo?

**Comment by Abs62** [comment]
I don't know. You also can try e-mail from GD/About.

**Pull request merged**
