### PR TITLE
Forvo api calls via https

### PR DESCRIPTION
**Pull request by max-yan**
About a month ago I started getting errors when using forvo. Like in issue #1222.
I didn't understand what happened but switching to https helped.

### CODE REVIEW

**Comment by loyukfai** [comment]
Any idea how to do it on Windows build?

Thanks in advance.

**Comment by loyukfai** [comment]
Thanks! Waiting for this to be committed and the next Windows build.

**Comment by loyukfai** [comment]
> About a month ago I started getting errors when using forvo. Like in issue #1222.
> I didn't understand what happened but switching to https helped.

Hi @max-yan do you know where can I find a Windows build containing this fix? Thanks in advance.

**Comment by max-yan** [comment]
> > About a month ago I started getting errors when using forvo. Like in issue #1222.
> > I didn't understand what happened but switching to https helped.
> 
> Hi @max-yan do you know where can I find a Windows build containing this fix? Thanks in advance.

https://github.com/goldendict/goldendict/issues/1254#issuecomment-618195726

**Comment by loyukfai** [comment]
Thanks... just prefer to download from the official early access builds, do you have any idea why it's not been updated for over an year?

Cheers.

**Pull request merged**
