### PR TITLE
Fix autostart bug

### PR DESCRIPTION
**Pull request by GD-fix**
Linux all.

### CODE REVIEW

**Comment by GD-fix** [comment]
P. S. See previous comments in closed pull request #927.
Last two commits were added automatically after corresponding changes in the master branch on GD-fix/goldendict.

**Comment by vedgy** [comment]
You can create a separate branch in your repository for each unrelated fix and base your merge request on that branch instead of bundling all fixes in the master branch.

**Comment by GD-fix** [comment]
Will pull request from separate branch appear there (on source master branch) too?

**Comment by GD-fix** [comment]
It doesn't work on kde4 (which has on ~ .kde4 subfolder, but not a .kde) too. So it doesn't work on all distributives, on which Goldendict can be compiled...

**Comment by vedgy** [comment]
> Will pull request from separate branch appear there (on source master branch) too?

Basing a pull request on a topic (not master) branch works perfectly well for me. If you take a look at my goldendict pull requests, you'll notice that each of them is based on a different branch from my goldendict fork. I also have a composite branch https://github.com/vedgy/goldendict/tree/all-my-fixes, which includes all fixes that form my personal goldendict "fork", which I'm running on my computer. I have made a mistake of basing one of the pull requests on my master branch, and now it's stuck there, because GitHub doesn't allow switching the source branch of a pull request.

> It doesn't work on kde4 (which has on ~ .kde4 subfolder, but not a .kde) too. So it doesn't work on all distributives, on which Goldendict can be compiled...

I suppose it had worked in KDE 4 back when its base directory was `~/.kde`. I guess it was replaced with `~/.kde4` at some point for disambiguation.

**Comment by GD-fix** [comment]
On old systems, which have kde4 with subfolder .kde, I think current Goldendict version can't be compiled...

The question is next: if I push button "New pull request" from my not master branch, will it appear here (on source repository master branch)?
And such another question: is it possible to do, that commits, made on source repository, will appear on my fork of it (in relevant branch)?

Thanks in advance.

**Comment by vedgy** [comment]
1. Yes.
2. Not automatically. You'll have to pull in the upstream master branch manually from time to time. Note that if there are no merge conflicts, then there is no need to update the branch, on which a pull request is based (to avoid complicating the pull request with many useless merge commits). You can keep trivial merge commits on your local machine.

**Comment by GD-fix** [comment]
So, if I want, that it will be possible for people to download upstream master branch with my fixes, I must (how I do now) each time delete my fork repository, fork original repository, do all my changes in my master branch (that people will download) and additionally (how I didn't do) create branches for each my fix and do pull request from each that branch.
Is it correct?

**Comment by vedgy** [comment]
No need to re-create the fork each time. You can simply keep one non-master branch for each fix. And dedicate a branch to all fixes (master or not, your choice). Assuming you name your branches `branch1`, `branch2`, `branch3` in your remote `origin`, choose the all-fixes branch name `my-fixes`, point a git remote `upstream` to the main goldendict repository, you can do the following:
```bash
git checkout -b my-fixes upstream/master
git pull origin branch1
git pull origin branch2
git pull origin branch3
git push -u origin my-fixes
```

After that, each time you want to update to the latest master, you can simply do:
```bash
git checkout my-fixes
git pull upstream master
git push
```

**Comment by GD-fix** [comment]
If more concrete: I need to update master branch of my fork https://github.com/GD-fix/goldendict by latest master branch of original https://github.com/goldendict/goldendict.
What must I do?

Thanks in advance.

**Comment by vedgy** [comment]
1. Make sure that you have both origin (GD-fix/goldendict) and upstream (goldendict/goldendict) remotes as described here: https://help.github.com/articles/configuring-a-remote-for-a-fork/

2. Switch to your master branch and ensure that it is up to date with your remote (origin).

3. Run the following commands:
```
git pull upstream master
git push origin master
```

The downside with the one-branch approach is that this pull request will have a useless merge commit. If you do this often, there will be many such merge commits. And if a maintainer finally merges this pull request, goldendict code history will contain scores of useless merge commits, which will make the history more difficult to visualize. But in this case I don't see it as a big issue, because I doubt that your current *master* branch will ever be merged as is. So if a maintainer gets interested in some of your fixes at some point in the future, [s]he can ask you to make a few changes first, then create a new clean pull request to be merged.

**Comment by GD-fix** [comment]
They aren't remote:

>git remote -v
> fatal: Not a git repository (or any parent up to mount parent )
> Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

I think, "Fork" button here doesn't work correctly...

**Comment by vedgy** [comment]
You have to enter (*cd*) the cloned *goldendict* directory first. Otherwise none of the git commands will work. The *Fork* button only creates another remote, to which I refer as *origin* in my previous post. So right now both of the remotes exist on the GitHub server. If you `git clone https://github.com/GD-fix/goldendict`, the *origin* remote will be created automatically. After that you can add another remote (*upstream* - *https://github.com/goldendict/goldendict*) an described in the GitHub help article here: https://help.github.com/articles/configuring-a-remote-for-a-fork/

**Comment by GD-fix** [comment]
So it isn't possible to update master branch of my fork https://github.com/GD-fix/goldendict by newer commits from master branch of original https://github.com/goldendict/goldendict (when both repositories are on GitHub)?

**Comment by vedgy** [comment]
It is possible, but you will also need a local repository for that.

**Comment by GD-fix** [comment]
New pull request #1007

**Pull request closed without merging**
