### PR TITLE
Parsing titles with char "/" correctly. Old way is for the outdated k…

### PR DESCRIPTION
**Pull request by jjzz**
…iwix zim file

### CODE REVIEW

**Comment by Abs62** [comment]
This patch broke links handling in old ZIM files. Support for new fashion should not broke existing dictionaries.

**Comment by jjzz** [comment]
Sorry for that.

In old kiwix zim, "/" has ambiguous meaning, for example:
- wikiquote, links like "/A/html/H/e/n/r/Henry_Miller.html" should be interpreted as "Henry_Miller", we need to get rid of anything before the last "/"
- wikibooks: "Variable"is a keyword, while "Algebra/Variables" is another keyword. we need to keep the "/" in it.

The old code didn't distinguish these very well, just simply erase anything before "/". so in "Algebra" page in wikibooks, if you click this link, you go to "Variables" instead of "Algebra/Variables". ( it's still possible to locate "Algebra/Variables" if you put "variable" in search box - just inconvenient )

"/" is used in keywords in wikibooks/wikiversity/wikisource etc.
Seems all new zim files have abandoned the unnecessary prefix like "/A/html/H/e/n/r/....".
I would suggest to upgrade to the lastest zim files.

If there are any other kind of broken links, let me know pls. I have deleted all old zim files, and couldn't test on that.

**Comment by Abs62** [comment]
>> I would suggest to upgrade to the lastest zim files  
I don't sure that all dictionaries with old-fashion links have new version without extra '/' chars. I think it needs to find solution to handle both variants correctly.

**Comment by Abs62** [comment]
Test last git changes, please.

**Comment by jjzz** [comment]
Cool!
It also solves another inconsistency I just found in kiwix zim, that is, wikibooks.zim and wikisource.zim treat  '/' as a symbol of chapter-seperator in titles differently.
Now I could click smoothly. Thanks!

**Pull request closed without merging**
