### PR TITLE
Compile goldendict in Qt5 and errors

### PR DESCRIPTION
**Pull request by ntung**
## I have compiled goldendict with Qt5 in Linux. There are plenty of errors as follows.

```
             from ./wordlist.hh:10,
             from build/ui_mainwindow.h:31,
             from mainwindow.hh:13,
             from main.cc:7:
```

/usr/include/qt5/QtGui/qopenglcontext.h:117:13: note: bool operator!=(const QOpenGLVersionProfile&, const QOpenGLVersionProfile&)
 inline bool operator!=(const QOpenGLVersionProfile &lhs, const QOpenGLVersionProfile &rhs)
             ^
/usr/include/qt5/QtGui/qopenglcontext.h:117:13: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const QOpenGLVersionProfile&’
In file included from /usr/include/qt5/QtGui/qopenglcontext.h:63:0,
                 from /usr/include/qt5/QtGui/QtGui:32,
                 from ./langcoder.hh:4,
                 from ./dictionary.hh:16,
                 from ./wordfinder.hh:14,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
/usr/include/qt5/QtGui/qopenglversionfunctions.h:107:13: note: bool operator!=(const QOpenGLVersionStatus&, const QOpenGLVersionStatus&)
 inline bool operator!=(const QOpenGLVersionStatus &lhs, const QOpenGLVersionStatus &rhs)
             ^
/usr/include/qt5/QtGui/qopenglversionfunctions.h:107:13: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const QOpenGLVersionStatus&’
In file included from /usr/include/qt5/QtGui/qsurface.h:46:0,
                 from /usr/include/qt5/QtGui/qoffscreensurface.h:46,
                 from /usr/include/qt5/QtGui/QtGui:31,
                 from ./langcoder.hh:4,
                 from ./dictionary.hh:16,
                 from ./wordfinder.hh:14,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
/usr/include/qt5/QtGui/qsurfaceformat.h:146:19: note: bool operator!=(const QSurfaceFormat&, const QSurfaceFormat&)
 Q_GUI_EXPORT bool operator!=(const QSurfaceFormat&, const QSurfaceFormat&);
                   ^
/usr/include/qt5/QtGui/qsurfaceformat.h:146:19: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const QSurfaceFormat&’
In file included from /usr/include/qt5/QtGui/qevent.h:58:0,
                 from /usr/include/qt5/QtGui/qaccessible.h:57,
                 from /usr/include/qt5/QtGui/QtGui:4,
                 from ./langcoder.hh:4,
                 from ./dictionary.hh:16,
                 from ./wordfinder.hh:14,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
/usr/include/qt5/QtGui/qvector2d.h:203:13: note: bool operator!=(const QVector2D&, const QVector2D&)
 inline bool operator!=(const QVector2D &v1, const QVector2D &v2)
             ^
/usr/include/qt5/QtGui/qvector2d.h:203:13: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const QVector2D&’
In file included from /usr/include/qt5/QtCore/QtCore:115:0,
                 from /usr/include/qt5/QtGui/QtGuiDepends:2,
                 from /usr/include/qt5/QtGui/QtGui:3,
                 from ./langcoder.hh:4,
                 from ./dictionary.hh:16,
                 from ./wordfinder.hh:14,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
/usr/include/qt5/QtCore/qarraydatapointer.h:196:13: note: template<class T> bool operator!=(const QArrayDataPointer<T>&, const QArrayDataPointer<T>&)
 inline bool operator!=(const QArrayDataPointer<T> &lhs, const QArrayDataPointer<T> &rhs)
             ^
/usr/include/qt5/QtCore/qarraydatapointer.h:196:13: note:   template argument deduction/substitution failed:
In file included from ./wordfinder.hh:14:0,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
./dictionary.hh:422:35: note:   ‘QAtomicInt’ is not derived from ‘const QArrayDataPointer<T>’
   { return FTS_index_completed != 0; }
                                   ^
In file included from /usr/include/qt5/QtCore/QtCore:72:0,
                 from /usr/include/qt5/QtGui/QtGuiDepends:2,
                 from /usr/include/qt5/QtGui/QtGui:3,
                 from ./langcoder.hh:4,
                 from ./dictionary.hh:16,
                 from ./wordfinder.hh:14,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
/usr/include/qt5/QtCore/qpointer.h:131:13: note: template<class T> bool operator!=(const QPointer<T>&, const QPointer<T>&)
 inline bool operator!= (const QPointer<T> &p1, const QPointer<T> &p2)
             ^
/usr/include/qt5/QtCore/qpointer.h:131:13: note:   template argument deduction/substitution failed:
In file included from ./wordfinder.hh:14:0,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
./dictionary.hh:422:35: note:   ‘QAtomicInt’ is not derived from ‘const QPointer<T>’
   { return FTS_index_completed != 0; }
                                   ^
In file included from /usr/include/qt5/QtCore/QtCore:72:0,
                 from /usr/include/qt5/QtGui/QtGuiDepends:2,
                 from /usr/include/qt5/QtGui/QtGui:3,
                 from ./langcoder.hh:4,
                 from ./dictionary.hh:16,
                 from ./wordfinder.hh:14,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
/usr/include/qt5/QtCore/qpointer.h:127:13: note: template<class T> bool operator!=(const QPointer<T>&, T_)
 inline bool operator!= (const QPointer<T> &p, T *o)
             ^
/usr/include/qt5/QtCore/qpointer.h:127:13: note:   template argument deduction/substitution failed:
In file included from ./wordfinder.hh:14:0,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
./dictionary.hh:422:35: note:   ‘QAtomicInt’ is not derived from ‘const QPointer<T>’
   { return FTS_index_completed != 0; }
                                   ^
In file included from /usr/include/qt5/QtCore/QtCore:72:0,
                 from /usr/include/qt5/QtGui/QtGuiDepends:2,
                 from /usr/include/qt5/QtGui/QtGui:3,
                 from ./langcoder.hh:4,
                 from ./dictionary.hh:16,
                 from ./wordfinder.hh:14,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
/usr/include/qt5/QtCore/qpointer.h:123:13: note: template<class T> bool operator!=(T_, const QPointer<T>&)
 inline bool operator!=(T _o, const QPointer<T> &p)
             ^
/usr/include/qt5/QtCore/qpointer.h:123:13: note:   template argument deduction/substitution failed:
In file included from ./wordfinder.hh:14:0,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
./dictionary.hh:422:35: note:   mismatched types ‘T_’ and ‘QAtomicInt’
   { return FTS_index_completed != 0; }
                                   ^
In file included from /usr/include/qt5/QtCore/QtCore:72:0,
                 from /usr/include/qt5/QtGui/QtGuiDepends:2,
                 from /usr/include/qt5/QtGui/QtGui:3,
                 from ./langcoder.hh:4,
                 from ./dictionary.hh:16,
                 from ./wordfinder.hh:14,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
/usr/include/qt5/QtCore/qpointer.h:119:13: note: template<class T> bool operator!=(const QPointer<T>&, const T_)
 inline bool operator!= (const QPointer<T> &p, const T *o)
             ^
/usr/include/qt5/QtCore/qpointer.h:119:13: note:   template argument deduction/substitution failed:
In file included from ./wordfinder.hh:14:0,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
./dictionary.hh:422:35: note:   ‘QAtomicInt’ is not derived from ‘const QPointer<T>’
   { return FTS_index_completed != 0; }
                                   ^
In file included from /usr/include/qt5/QtCore/QtCore:72:0,
                 from /usr/include/qt5/QtGui/QtGuiDepends:2,
                 from /usr/include/qt5/QtGui/QtGui:3,
                 from ./langcoder.hh:4,
                 from ./dictionary.hh:16,
                 from ./wordfinder.hh:14,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
/usr/include/qt5/QtCore/qpointer.h:115:13: note: template<class T> bool operator!=(const T_, const QPointer<T>&)
 inline bool operator!=(const T _o, const QPointer<T> &p)
             ^
/usr/include/qt5/QtCore/qpointer.h:115:13: note:   template argument deduction/substitution failed:
In file included from ./wordfinder.hh:14:0,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
./dictionary.hh:422:35: note:   mismatched types ‘const T_’ and ‘QAtomicInt’
   { return FTS_index_completed != 0; }
                                   ^
In file included from /usr/include/qt5/QtCore/QtCore:66:0,
                 from /usr/include/qt5/QtGui/QtGuiDepends:2,
                 from /usr/include/qt5/QtGui/QtGui:3,
                 from ./langcoder.hh:4,
                 from ./dictionary.hh:16,
                 from ./wordfinder.hh:14,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
/usr/include/qt5/QtCore/qmetaobject.h:180:13: note: bool operator!=(const QMetaMethod&, const QMetaMethod&)
 inline bool operator!=(const QMetaMethod &m1, const QMetaMethod &m2)
             ^
/usr/include/qt5/QtCore/qmetaobject.h:180:13: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const QMetaMethod&’
In file included from /usr/include/qt5/QtWidgets/qwidget.h:47:0,
                 from /usr/include/qt5/QtWidgets/qabstractspinbox.h:45,
                 from /usr/include/qt5/QtWidgets/qstyleoption.h:46,
                 from /usr/include/qt5/QtWidgets/QStyleOption:1,
                 from gdappstyle.hh:13,
                 from main.cc:6:
/usr/include/qt5/QtCore/qmargins.h:143:30: note: bool operator!=(const QMargins&, const QMargins&)
 Q_DECL_CONSTEXPR inline bool operator!=(const QMargins &m1, const QMargins &m2)
                              ^
/usr/include/qt5/QtCore/qmargins.h:143:30: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const QMargins&’
In file included from /usr/include/qt5/QtWidgets/qstyleoption.h:45:0,
                 from /usr/include/qt5/QtWidgets/QStyleOption:1,
                 from gdappstyle.hh:13,
                 from main.cc:6:
/usr/include/qt5/QtCore/qvariant.h:569:13: note: bool operator!=(const QVariant&, const QVariantComparisonHelper&)
 inline bool operator!=(const QVariant &v1, const QVariantComparisonHelper &v2)
             ^
/usr/include/qt5/QtCore/qvariant.h:569:13: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const QVariant&’
In file included from /usr/include/qt5/QtCore/qsharedpointer.h:50:0,
                 from /usr/include/qt5/QtGui/qpixmap.h:49,
                 from /usr/include/qt5/QtGui/qicon.h:48,
                 from /usr/include/qt5/QtGui/QIcon:1,
                 from main.cc:5:
/usr/include/qt5/QtCore/qsharedpointer_impl.h:716:6: note: template<class T, class X> bool operator!=(const QSharedPointer<T>&, const QWeakPointer<X>&)
 bool operator!=(const QSharedPointer<T> &ptr1, const QWeakPointer<X> &ptr2)
      ^
/usr/include/qt5/QtCore/qsharedpointer_impl.h:716:6: note:   template argument deduction/substitution failed:
In file included from ./wordfinder.hh:14:0,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
./dictionary.hh:422:35: note:   ‘QAtomicInt’ is not derived from ‘const QSharedPointer<T>’
   { return FTS_index_completed != 0; }
                                   ^
In file included from /usr/include/qt5/QtCore/qsharedpointer.h:50:0,
                 from /usr/include/qt5/QtGui/qpixmap.h:49,
                 from /usr/include/qt5/QtGui/qicon.h:48,
                 from /usr/include/qt5/QtGui/QIcon:1,
                 from main.cc:5:
/usr/include/qt5/QtCore/qsharedpointer_impl.h:705:6: note: template<class T, class X> bool operator!=(const T_, const QSharedPointer<T>&)
 bool operator!=(const T *ptr1, const QSharedPointer<X> &ptr2)
      ^
/usr/include/qt5/QtCore/qsharedpointer_impl.h:705:6: note:   template argument deduction/substitution failed:
In file included from ./wordfinder.hh:14:0,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
./dictionary.hh:422:35: note:   mismatched types ‘const T_’ and ‘QAtomicInt’
   { return FTS_index_completed != 0; }
                                   ^
In file included from /usr/include/qt5/QtCore/qsharedpointer.h:50:0,
                 from /usr/include/qt5/QtGui/qpixmap.h:49,
                 from /usr/include/qt5/QtGui/qicon.h:48,
                 from /usr/include/qt5/QtGui/QIcon:1,
                 from main.cc:5:
/usr/include/qt5/QtCore/qsharedpointer_impl.h:700:6: note: template<class T, class X> bool operator!=(const QSharedPointer<T>&, const X_)
 bool operator!=(const QSharedPointer<T> &ptr1, const X *ptr2)
      ^
/usr/include/qt5/QtCore/qsharedpointer_impl.h:700:6: note:   template argument deduction/substitution failed:
In file included from ./wordfinder.hh:14:0,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
./dictionary.hh:422:35: note:   ‘QAtomicInt’ is not derived from ‘const QSharedPointer<T>’
   { return FTS_index_completed != 0; }
                                   ^
In file included from /usr/include/qt5/QtCore/qsharedpointer.h:50:0,
                 from /usr/include/qt5/QtGui/qpixmap.h:49,
                 from /usr/include/qt5/QtGui/qicon.h:48,
                 from /usr/include/qt5/QtGui/QIcon:1,
                 from main.cc:5:
/usr/include/qt5/QtCore/qsharedpointer_impl.h:684:6: note: template<class T, class X> bool operator!=(const QSharedPointer<T>&, const QSharedPointer<T>&)
 bool operator!=(const QSharedPointer<T> &ptr1, const QSharedPointer<X> &ptr2)
      ^
/usr/include/qt5/QtCore/qsharedpointer_impl.h:684:6: note:   template argument deduction/substitution failed:
In file included from ./wordfinder.hh:14:0,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
./dictionary.hh:422:35: note:   ‘QAtomicInt’ is not derived from ‘const QSharedPointer<T>’
   { return FTS_index_completed != 0; }
                                   ^
In file included from /usr/include/qt5/QtCore/qdatastream.h:47:0,
                 from /usr/include/qt5/QtCore/qstringlist.h:46,
                 from /usr/include/qt5/QtGui/qcolor.h:47,
                 from /usr/include/qt5/QtGui/qpixmap.h:46,
                 from /usr/include/qt5/QtGui/qicon.h:48,
                 from /usr/include/qt5/QtGui/QIcon:1,
                 from main.cc:5:
/usr/include/qt5/QtCore/qpair.h:87:24: note: template<class T1, class T2> bool operator!=(const QPair<T, U>&, const QPair<T, U>&)
 Q_INLINE_TEMPLATE bool operator!=(const QPair<T1, T2> &p1, const QPair<T1, T2> &p2)
                        ^
/usr/include/qt5/QtCore/qpair.h:87:24: note:   template argument deduction/substitution failed:
In file included from ./wordfinder.hh:14:0,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
./dictionary.hh:422:35: note:   ‘QAtomicInt’ is not derived from ‘const QPair<T, U>’
   { return FTS_index_completed != 0; }
                                   ^
In file included from /usr/include/qt5/QtCore/qmetatype.h:48:0,
                 from /usr/include/qt5/QtCore/qobject.h:56,
                 from /usr/include/qt5/QtCore/qiodevice.h:47,
                 from /usr/include/qt5/QtCore/qdatastream.h:46,
                 from /usr/include/qt5/QtCore/qstringlist.h:46,
                 from /usr/include/qt5/QtGui/qcolor.h:47,
                 from /usr/include/qt5/QtGui/qpixmap.h:46,
                 from /usr/include/qt5/QtGui/qicon.h:48,
                 from /usr/include/qt5/QtGui/QIcon:1,
                 from main.cc:5:
/usr/include/qt5/QtCore/qvarlengtharray.h:427:6: note: template<class T, int Prealloc1, int Prealloc2> bool operator!=(const QVarLengthArray<T, Prealloc1>&, const QVarLengthArray<T, Prealloc2>&)
 bool operator!=(const QVarLengthArray<T, Prealloc1> &l, const QVarLengthArray<T, Prealloc2> &r)
      ^
/usr/include/qt5/QtCore/qvarlengtharray.h:427:6: note:   template argument deduction/substitution failed:
In file included from ./wordfinder.hh:14:0,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
./dictionary.hh:422:35: note:   ‘QAtomicInt’ is not derived from ‘const QVarLengthArray<T, Prealloc1>’
   { return FTS_index_completed != 0; }
                                   ^
In file included from /usr/include/qt5/QtCore/qobject.h:49:0,
                 from /usr/include/qt5/QtCore/qiodevice.h:47,
                 from /usr/include/qt5/QtCore/qdatastream.h:46,
                 from /usr/include/qt5/QtCore/qstringlist.h:46,
                 from /usr/include/qt5/QtGui/qcolor.h:47,
                 from /usr/include/qt5/QtGui/qpixmap.h:46,
                 from /usr/include/qt5/QtGui/qicon.h:48,
                 from /usr/include/qt5/QtGui/QIcon:1,
                 from main.cc:5:
/usr/include/qt5/QtCore/qstring.h:1333:13: note: bool operator!=(const QStringRef&, QLatin1String)
 inline bool operator!=(const QStringRef &s1, QLatin1String s2)
             ^
/usr/include/qt5/QtCore/qstring.h:1333:13: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const QStringRef&’
/usr/include/qt5/QtCore/qstring.h:1329:13: note: bool operator!=(QLatin1String, const QStringRef&)
 inline bool operator!=(QLatin1String s1, const QStringRef &s2)
             ^
/usr/include/qt5/QtCore/qstring.h:1329:13: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘QLatin1String’
/usr/include/qt5/QtCore/qstring.h:1326:13: note: bool operator!=(const QStringRef&, const QString&)
 inline bool operator!=(const QStringRef &s1,const QString &s2)
             ^
/usr/include/qt5/QtCore/qstring.h:1326:13: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const QStringRef&’
/usr/include/qt5/QtCore/qstring.h:1322:13: note: bool operator!=(const QString&, const QStringRef&)
 inline bool operator!=(const QString &s1,const QStringRef &s2)
             ^
/usr/include/qt5/QtCore/qstring.h:1322:13: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const QString&’
/usr/include/qt5/QtCore/qstring.h:1319:13: note: bool operator!=(const QStringRef&, const QStringRef&)
 inline bool operator!=(const QStringRef &s1,const QStringRef &s2)
             ^
/usr/include/qt5/QtCore/qstring.h:1319:13: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const QStringRef&’
/usr/include/qt5/QtCore/qstring.h:1042:32: note: bool operator!=(const char_, QLatin1String)
 inline QT_ASCII_CAST_WARN bool operator!=(const char _s1, QLatin1String s2)
                                ^
/usr/include/qt5/QtCore/qstring.h:1042:32: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const char_’
/usr/include/qt5/QtCore/qstring.h:985:13: note: bool operator!=(QLatin1String, QLatin1String)
 inline bool operator!=(QLatin1String s1, QLatin1String s2)
             ^
/usr/include/qt5/QtCore/qstring.h:985:13: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘QLatin1String’
/usr/include/qt5/QtCore/qstring.h:981:13: note: bool operator!=(const QString&, QString::Null)
 inline bool operator!=(const QString &s, QString::Null) { return !s.isNull(); }
             ^
/usr/include/qt5/QtCore/qstring.h:981:13: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const QString&’
/usr/include/qt5/QtCore/qstring.h:980:13: note: bool operator!=(QString::Null, const QString&)
 inline bool operator!=(QString::Null, const QString &s) { return !s.isNull(); }
             ^
/usr/include/qt5/QtCore/qstring.h:980:13: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘QString::Null’
/usr/include/qt5/QtCore/qstring.h:979:13: note: bool operator!=(QString::Null, QString::Null)
 inline bool operator!=(QString::Null, QString::Null) { return false; }
             ^
/usr/include/qt5/QtCore/qstring.h:979:13: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘QString::Null’
/usr/include/qt5/QtCore/qstring.h:1360:32: note: bool operator!=(const char_, const QStringRef&)
 inline QT_ASCII_CAST_WARN bool operator!=(const char *s1, const QStringRef &s2)
                                ^
/usr/include/qt5/QtCore/qstring.h:1360:32: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const char_’
/usr/include/qt5/QtCore/qstring.h:1029:32: note: bool operator!=(const char_, const QString&)
 inline QT_ASCII_CAST_WARN bool operator!=(const char *s1, const QString &s2)
                                ^
/usr/include/qt5/QtCore/qstring.h:1029:32: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const char_’
In file included from /usr/include/qt5/QtCore/qstring.h:46:0,
                 from /usr/include/qt5/QtCore/qobject.h:49,
                 from /usr/include/qt5/QtCore/qiodevice.h:47,
                 from /usr/include/qt5/QtCore/qdatastream.h:46,
                 from /usr/include/qt5/QtCore/qstringlist.h:46,
                 from /usr/include/qt5/QtGui/qcolor.h:47,
                 from /usr/include/qt5/QtGui/qpixmap.h:46,
                 from /usr/include/qt5/QtGui/qicon.h:48,
                 from /usr/include/qt5/QtGui/QIcon:1,
                 from main.cc:5:
/usr/include/qt5/QtCore/qbytearray.h:547:13: note: bool operator!=(const char_, const QByteArray&)
 inline bool operator!=(const char *a1, const QByteArray &a2)
             ^
/usr/include/qt5/QtCore/qbytearray.h:547:13: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const char_’
/usr/include/qt5/QtCore/qbytearray.h:545:13: note: bool operator!=(const QByteArray&, const char_)
 inline bool operator!=(const QByteArray &a1, const char *a2)
             ^
/usr/include/qt5/QtCore/qbytearray.h:545:13: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const QByteArray&’
/usr/include/qt5/QtCore/qbytearray.h:543:13: note: bool operator!=(const QByteArray&, const QByteArray&)
 inline bool operator!=(const QByteArray &a1, const QByteArray &a2)
             ^
/usr/include/qt5/QtCore/qbytearray.h:543:13: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const QByteArray&’
In file included from /usr/include/qt5/QtCore/qstring.h:45:0,
                 from /usr/include/qt5/QtCore/qobject.h:49,
                 from /usr/include/qt5/QtCore/qiodevice.h:47,
                 from /usr/include/qt5/QtCore/qdatastream.h:46,
                 from /usr/include/qt5/QtCore/qstringlist.h:46,
                 from /usr/include/qt5/QtGui/qcolor.h:47,
                 from /usr/include/qt5/QtGui/qpixmap.h:46,
                 from /usr/include/qt5/QtGui/qicon.h:48,
                 from /usr/include/qt5/QtGui/QIcon:1,
                 from main.cc:5:
/usr/include/qt5/QtCore/qchar.h:514:13: note: bool operator!=(QChar, QChar)
 inline bool operator!=(QChar c1, QChar c2) { return c1.unicode() != c2.unicode(); }
             ^
/usr/include/qt5/QtCore/qchar.h:514:13: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘QChar’
In file included from /usr/include/qt5/QtCore/qdatastream.h:45:0,
                 from /usr/include/qt5/QtCore/qstringlist.h:46,
                 from /usr/include/qt5/QtGui/qcolor.h:47,
                 from /usr/include/qt5/QtGui/qpixmap.h:46,
                 from /usr/include/qt5/QtGui/qicon.h:48,
                 from /usr/include/qt5/QtGui/QIcon:1,
                 from main.cc:5:
/usr/include/qt5/QtCore/qscopedpointer.h:188:13: note: template<class T, class Cleanup> bool operator!=(const QScopedPointer<T, Cleanup>&, const QScopedPointer<T, Cleanup>&)
 inline bool operator!=(const QScopedPointer<T, Cleanup> &lhs, const QScopedPointer<T, Cleanup> &rhs)
             ^
/usr/include/qt5/QtCore/qscopedpointer.h:188:13: note:   template argument deduction/substitution failed:
In file included from ./wordfinder.hh:14:0,
                 from ./wordlist.hh:10,
                 from build/ui_mainwindow.h:31,
                 from mainwindow.hh:13,
                 from main.cc:7:
./dictionary.hh:422:35: note:   ‘QAtomicInt’ is not derived from ‘const QScopedPointer<T, Cleanup>’
   { return FTS_index_completed != 0; }
                                   ^
In file included from /usr/include/qt5/QtGui/qpaintdevice.h:46:0,
                 from /usr/include/qt5/QtGui/qpixmap.h:45,
                 from /usr/include/qt5/QtGui/qicon.h:48,
                 from /usr/include/qt5/QtGui/QIcon:1,
                 from main.cc:5:
/usr/include/qt5/QtCore/qrect.h:776:30: note: bool operator!=(const QRectF&, const QRectF&)
 Q_DECL_CONSTEXPR inline bool operator!=(const QRectF &r1, const QRectF &r2)
                              ^
/usr/include/qt5/QtCore/qrect.h:776:30: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const QRectF&’
/usr/include/qt5/QtCore/qrect.h:450:30: note: bool operator!=(const QRect&, const QRect&)
 Q_DECL_CONSTEXPR inline bool operator!=(const QRect &r1, const QRect &r2)
                              ^
/usr/include/qt5/QtCore/qrect.h:450:30: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const QRect&’
In file included from /usr/include/qt5/QtCore/qrect.h:46:0,
                 from /usr/include/qt5/QtGui/qpaintdevice.h:46,
                 from /usr/include/qt5/QtGui/qpixmap.h:45,
                 from /usr/include/qt5/QtGui/qicon.h:48,
                 from /usr/include/qt5/QtGui/QIcon:1,
                 from main.cc:5:
/usr/include/qt5/QtCore/qpoint.h:342:30: note: bool operator!=(const QPointF&, const QPointF&)
 Q_DECL_CONSTEXPR inline bool operator!=(const QPointF &p1, const QPointF &p2)
                              ^
/usr/include/qt5/QtCore/qpoint.h:342:30: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const QPointF&’
/usr/include/qt5/QtCore/qpoint.h:160:30: note: bool operator!=(const QPoint&, const QPoint&)
 Q_DECL_CONSTEXPR inline bool operator!=(const QPoint &p1, const QPoint &p2)
                              ^
/usr/include/qt5/QtCore/qpoint.h:160:30: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const QPoint&’
In file included from /usr/include/qt5/QtGui/qicon.h:46:0,
                 from /usr/include/qt5/QtGui/QIcon:1,
                 from main.cc:5:
/usr/include/qt5/QtCore/qsize.h:331:30: note: bool operator!=(const QSizeF&, const QSizeF&)
 Q_DECL_CONSTEXPR inline bool operator!=(const QSizeF &s1, const QSizeF &s2)
                              ^
/usr/include/qt5/QtCore/qsize.h:331:30: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const QSizeF&’
/usr/include/qt5/QtCore/qsize.h:166:30: note: bool operator!=(const QSize&, const QSize&)
 Q_DECL_CONSTEXPR inline bool operator!=(const QSize &s1, const QSize &s2)
                              ^
/usr/include/qt5/QtCore/qsize.h:166:30: note:   no known conversion for argument 1 from ‘QAtomicInt’ to ‘const QSize&’
In file included from mainwindow.hh:25:0,
                 from main.cc:7:
hotkeywrapper.hh: At global scope:
hotkeywrapper.hh:105:36: error: ‘XPointer’ has not been declared
   static void recordEventCallback( XPointer, XRecordInterceptData \* );
                                    ^
hotkeywrapper.hh:105:46: error: ‘XRecordInterceptData’ has not been declared
   static void recordEventCallback( XPointer, XRecordInterceptData \* );
                                              ^
hotkeywrapper.hh:108:27: error: ‘XRecordInterceptData’ has not been declared
   void handleRecordEvent( XRecordInterceptData \* );
                           ^
hotkeywrapper.hh:113:3: error: ‘KeyCode’ does not name a type
   KeyCode lShiftCode, rShiftCode, lCtrlCode, rCtrlCode, lAltCode, rAltCode,
   ^
hotkeywrapper.hh:118:3: error: ‘Display’ does not name a type
   Display \* dataDisplay;
   ^
hotkeywrapper.hh:119:3: error: ‘XRecordRange’ does not name a type
   XRecordRange \* recordRange;
   ^
hotkeywrapper.hh:120:3: error: ‘XRecordContext’ does not name a type
   XRecordContext recordContext;
   ^
hotkeywrapper.hh:121:3: error: ‘XRecordClientSpec’ does not name a type
   XRecordClientSpec recordClientSpec;
   ^
main.cc: In function ‘int main(int, char__)’:
main.cc:231:42: error: ‘qInstallMsgHandler’ was not declared in this scope
     qInstallMsgHandler( gdMessageHandler );
                                          ^
make: *_\* [build/main.o] Error 1

### CODE REVIEW

**Comment by Abs62** [comment]
For build with Qt5 take branch "qt4x5" from git, not "master".

**Comment by hosiet** [comment]
@ntung Now that Qt5 support is pretty good in master branch, could this PR be closed?

**Comment by xiaoyifang** [comment]
can be closed

**Comment by vedgy** [comment]
This pull request adds lots of compiled binaries and its goal is obsolete.

**Pull request closed without merging**
