### PR TITLE
Update fa_IR.ts

### PR DESCRIPTION
**Pull request by hota64**
correcting some lines.

### CODE REVIEW

**Comment by vedgy** [comment]
There was a confusion with 3 other pull reqeusts by @hota64, which I just closed. So I'm not sure whether this 4th pull request is good. Can any Persian speaker please review this small change?

**Comment by ilius** [comment]
It's okay. But can be improved.

**Comment by vedgy** [comment]
> It's okay. But can be improved.

But no one cares enough to improve it :)

Is it at least an improvement over the existing translation?

**Comment by ilius** [comment]
Yes.

**Comment by Abs62** [comment]
OK.

**Pull request merged**
