### PR TITLE
Support conversion between simplified and traditional Chinese characters

### PR DESCRIPTION
**Pull request by 0x1997**
There's a new dependency on [OpenCC](https://github.com/BYVoid/OpenCC) which may need to be bundled into the repo for Windows and Mac OS X users. But I don't have these systems at hand. So currently it's Linux-only.

### CODE REVIEW

**Comment by Abs62** [comment]
1. GD use own realization of wchar/wstring type. The ones same as std::xxx under Linux and MacOS but different under Windows (see wstring.hh). With std::wstring GD don't compile under Windows.

2. In loaddictionaries.cc Chinese::makeDictionaries called even if defined NO_CHINESE_CONVERSION_SUPPORT.

3. On "Transliteration" tab in dictionaries dialog options for Chinese conversionare presented and works even if defined NO_CHINESE_CONVERSION_SUPPORT.

4. Where should be placed OpenCC configuration and dictionary files (at least under Windows and MacOS)? I think the ones should be placed in separate directory.  
PS. As I see OpenCC use standard fopen(char *), it may leads to problem under Windows if path will contain non-ASCII characters.

5. You don't handle OpenCC library exceptions and GD crashed (for example if configuration or dictionary file not found). I think it needs at least don't allow to crash. And to fix warning in log (see gdWarning function).

6. I think it needs to write to readme.md new dependencies and new qmake key.

**Comment by 0x1997** [comment]
> Where should be placed OpenCC configuration and dictionary files (at least under Windows and MacOS)? I think the ones should be placed in separate directory.

Yes. The data directory can be specified as [`PKGDATADIR`](https://github.com/BYVoid/OpenCC/blob/master/src%2FCommon.hpp#L87) when building OpenCC
See also https://github.com/rime/librime/blob/develop/Makefile.thirdparty#L46-L48

> As I see OpenCC use standard fopen(char *), it may leads to problem under Windows if path will contain non-ASCII characters.

Would it still be an issue if a relative path without non-ASCII characters is passed into fopen?

**Comment by Abs62** [comment]
I think to use relative path we should to set correct current work directory beforehand.

**Comment by Abs62** [comment]
2. You forget to include "stdexcept" header in chinese.cc".

3. Why now "Transliteration" tab is default in dictionaries dialog?

**Pull request merged**
