### PR TITLE
Dictionaries dialog: always show Maximize button

### LINKED ISSUE #1359: [function] to adds the "maximize" button on  the Dictionary(F3) window
Add the Maximization button on the dictionary window (F3) 

image

### PR DESCRIPTION
**Pull request by vedgy**
See the commit message for details. Closes #1359.

*If anyone checks the window buttons in Dictionaries dialog with this commit on Mac or GNU/Linux desktop environments/window managers other than Xfce and KDE Plasma, then describes them in a comment, I can amend the commit message with this information.*

### CODE REVIEW

**Comment by nonwill** [comment]
On Windows it goes well with the following changes：
```c++
#if QT_VERSION >= QT_VERSION_CHECK(5, 9, 0)  
  setWindowFlag(Qt::WindowMinMaxButtonsHint, true);  
#else  
  setWindowFlags(windowFlags() | Qt::WindowMinMaxButtonsHint);  
#endif
```

And initiating QDialog with "Qt::WindowSystemMenuHint | Qt::WindowMaximizeButtonHint | Qt::WindowCloseButtonHint" as 914c39c just made the minimize button disabled:

**Comment by vedgy** [comment]
@nonwill, thank you for checking! As stated in the commit message, I don't believe the Minimize button is useful for this dialog. So being disabled should be OK. Usually dialogs don't have the Minimize button under Xfce and probably on Windows too.

Do you know of some use case for this Minimize button? What happens when you minimize the Dictionaries dialog? Is the main window minimized as well? If not, can it be interacted with or is all input still blocked by the minimized Dictionaries dialog?

**Comment by nonwill** [comment]
> I don't believe the Minimize button is useful for this dialog

Yes, I just tested that the Minimize button is useless here but only minimized the Dictionaries dialog. And when the Dictionaries dialog has been minimized, the main window is still blocked by the minimized Dictionaries dialog.

**Comment by vedgy** [comment]
Thanks for checking. I kept the commit's code changes intact and amended the commit message.

**Pull request merged**
