### PR TITLE
Fix missing key shortcut for menubar "search" list

### PR DESCRIPTION
**Pull request by hosiet**
The first commit fixes the bug for "search" menu in menubar by adding missing `&amp;` for menubar in `mainwindow.ui`.

The second commit would refresh translations since translations in last PR won't work before running `lupdate` again, which is pretty strange.

### CODE REVIEW

**Comment by hosiet** [comment]
I'd drop this PR for now due to conflicts. Will try again later with a more specific/smaller commit.

**Comment by darnn** [comment]
Wait, sorry to, like, barge in on this, but is it about how you can't reliably focus on the search textbox using alt+d?

**Comment by hosiet** [comment]
Nope, alt + d works fine.

It's about the missing `&amp;`, which makes the menu bar looks ugly under some Asian locale (e.g. Chinese, which adds acclerate key explicitly in translation for alt+SOMEKEY shortcut). Also the "search" menu in menubar works differently from "alt+D".

**Comment by darnn** [comment]
Ah, okay, thanks. Also, for me, on Windows, in 1.5.0-RC2-85-g473cb2b w/Qt 4.8.6, alt+d doesn't work entirely as expected (e.g. if the focus is already on the textbox GD will instead treat alt+d as just alt, and highlight the file menu), but I can just submit a separate bug report about that.

**Pull request closed without merging**
