### PR TITLE
Add -h, --help and --help-gui command line options

### PR DESCRIPTION
**Pull request by vedgy**
In-app help/reference already documents available command line options.
However, command line users expect the `goldendict --help` command to
print usage help. Almost every program that supports command line
options has the `--help` option, at least on GNU/Linux.
    
Add the `--help-gui` option mostly for the benefit of MS Windows users, in
case GoldenDict cannot print to standard output.

-------------------------
The following comments have suggested the `--help` option:
https://github.com/goldendict/goldendict/issues/911#issuecomment-362895559
https://github.com/goldendict/goldendict/issues/1625#issuecomment-1528887796

### CODE REVIEW

**Comment by Abs62** [comment]
Under Windows GD have no console at all, therefore the "-h" and "--help" options are pointless. I think in this case these options should work like "--help-gui" in your commit. Maybe this "--help-gui" is redundant.

**Comment by vedgy** [comment]
Done. Screenshots:
console-help
gui-help

I think increasing message box width would improve the help message's readability. But somehow the approaches proposed [here](https://stackoverflow.com/questions/37668820/how-can-i-resize-qmessagebox) aren't very attractive. Besides, what does and doesn't fit into a single line depends on system font size configuration.

**Comment by vedgy** [comment]
@Abs62, what about my question above?

> In case this pull request is merged, should we duplicate the help message in the [goldendict-help](https://github.com/Abs62/goldendict-help) repository? Or simply advice users to run goldendict --help/goldendict --help-gui in the in-app help/reference?

Running `goldendict --help` is easy and common enough on GNU/Linux. But is reading the in-app documentation substantially more convenient on Windows and macOS?

**Comment by Abs62** [comment]
I think it will be enough to add a description of the "-h, --help" option. Other options already described there.

**Pull request merged**
