### PR TITLE
Create fa_IR.ts

### PR DESCRIPTION
**Pull request by hota64**
The first and Complete Persian Translation of GD.
I have uploaded it because off chulai inactivity, he told me the it will be uploaded by himself.

### CODE REVIEW

**Comment by hosiet** [comment]
@Abs62 Now we have fa_IR.ts in locales/ directory, this PR can be closed safely.

**Comment by xiaoyifang** [comment]
can be closed

**Comment by vedgy** [comment]
@hota64, how about closing this pull request and #422? Or is your translation superior to GoldenDict's current Persian translation https://github.com/goldendict/goldendict/blob/master/locale/fa_IR.ts?

**Comment by vedgy** [comment]
Just checked the diff: the `<location>` elements are removed for some reason. Without these tags, the translation is probably unusable.

**Pull request closed without merging**
