### PR TITLE
Add an option to disable scan popup inside goldendict

### PR DESCRIPTION
**Pull request by vedgy**
This pull request implements one of two feature requests in issue #606.
See the commit messages for details.

### CODE REVIEW

**Comment by Abs62** [comment]
The "ignoreOwnClipboardChanges" is a Linux-specific option. It should always be hidden under other OS even the "trackClipboardChanges" option is turned on via config file. Using of the "isTrackingClipboardChanges()" function result as condition don't guarantee such behaviour.

**Comment by vedgy** [comment]
Why is it a Linux-specific option? If I understand correctly, copying text in Goldendict triggers scan popup on Windows and Mac if the hidden `trackClipboardChanges` option is enabled. I suppose some users might want to copy text in the scan popup window without automatically navigating to the definition of the copied text. The same reasoning applies to copying text in the main window when the *Send translated word to main window* option is enabled.

**Comment by Abs62** [comment]
A least under Windows scan popup should not be used without key modifiers (in my opinion) because it used some hack metod to determine word under mouse cursor which potentially can conflict with other programs. I don't want to add any options to relieve work without modifiers.

**Comment by vedgy** [comment]
OK, I'll hide the option on non-X11 platforms.

Implementation questions:
1. Would you like me to revert the second commit (the `isTrackingClipboardChanges()` function) ?
2. Is it OK to force-push the requested change to this branch `vedgy:option-to-disable-scan-popup-inside-goldendict`? For example I can remove the first commit and add 3 lines that hide the checkbox `#ifndef HAVE_X11` into the first commit.

**Comment by Abs62** [comment]
OK. I has not yet merge today pull requests.

BTW, for (OS/dictionary type/Qt version)-specific commits name its with corresponding prefix, please (look GD commits list for example). To simplify search commits which may affect some specific feature afterwards.

**Comment by vedgy** [comment]
Done.

Diff with the previous first commit:

```udiff
diff --git a/preferences.cc b/preferences.cc
index fa6de4e..1fe8f8c 100644
--- a/preferences.cc
+++ b/preferences.cc
@@ -243,6 +243,7 @@ Preferences::Preferences( QWidget * parent, Config::Class & cfg_ ):
   ui.showScanFlag->setChecked( p.showScanFlag);
 #else
   ui.showScanFlag->hide();
+  ui.ignoreOwnClipboardChanges->hide();
 #endif
 
   // Sound
diff --git a/scanpopup.cc b/scanpopup.cc
index d9aafbc..b2464e9 100644
--- a/scanpopup.cc
+++ b/scanpopup.cc
@@ -489,8 +489,10 @@ void ScanPopup::clipboardChanged( QClipboard::Mode m )
 {
   if ( !isScanningEnabled )
     return;
+#ifdef HAVE_X11
   if( cfg.preferences.ignoreOwnClipboardChanges && ownsClipboardMode( m ) )
     return;
+#endif
 
   GD_DPRINTF( "clipboard changed\n" );
```

**Pull request merged**
