### PR TITLE
Search alternatives for plural(-es,-s), Past tense(-ed), -ing, phrasal verbs  (only Dict=StarDict and LangFrom=En)

### PR DESCRIPTION
**Pull request by PavelPoroskov**
useful when search with scan popup: 
// search alternatives 
//    for plural or 
//    for Past tense of regular verbs, 
//    for -ing,
//    for Phrasal Verbs
//
//    (not in dictionary): books --> book (in dictionary),
//    (not in dictionary): classes --> class (in dictionary),
//    (not in dictionary): parties --> party (in dictionary),
        // knives --> knife
        // wolves --> wolf
//
//    (not in dictionary): worked --> work (in dictionary)
//    (not in dictionary): leveraged --> leverage (in dictionary)
//
//    (not in dictionary): clanging --> clang (in dictionary)
//    (not in dictionary): icing --> ice (in dictionary)
//
//    (not in dictionary): reaching out --> reach out (in dictionary)
//    (not in dictionary): pushes out --> push out (in dictionary)
//    (not in dictionary): pushed out --> push out (in dictionary)

### CODE REVIEW

**Comment by PavelPoroskov** [comment]
need to polish

**Comment by vedgy** [comment]
@Abs62 described the existing goldendict solution for word forms in a comment to #528: Sources/Morphology tab in Dictionaries. Is there any benefit in your proposed implementation other than not depending on Myspell/Hunspell?

**Comment by PavelPoroskov** [comment]
My solution work with phrasal verbs better: "tern them on" --> "tern on".
It is easy to highlight whole phrase, press Cntrl+C+C, and get answer at
once.

I have discarded my pull request because my solution is not enough general
(it is placed in stardict.cc and for only English language).
If to suggest this solution it is need to relocate one to dedicated file
and to call from articlemaker.cc.


Solution with Hunspell dictionaries  #528
<https://github.com/goldendict/goldendict/issues/528> not worked on my pc
(Ubunty 16.04).
Perhaps, I had downloaded wrong dictionaries (.aff+.dic).
I have fixed it with steps:
1) sudo apt install hunspell (I had not errors before and used qmake-qt4
"CONFIG+=old_hunspell" && make)
2) set path /usr/share/hunspell for Sources/Morphology tab in Dictionaries

Hunspell had installed with en_US dictionary in /usr/share/hunspell.

**Comment by PavelPoroskov** [comment]
//fix for previous comment.
My solution work with phrasal verbs better: "turn them on" --> "turn on".

**Comment by vedgy** [comment]
You could just edit your comment instead of posting the second one :)

If I understand correctly, Hunspell works for you now. Do you still want to work on your alternative solution? I realize that it may work better sometimes, but it covers only some specific cases and is likely to produce false positives. Perhaps it would be better to try and improve Hunspell integration instead...

**Comment by PavelPoroskov** [comment]
I use my solution.
Now i use it with hunspell. First my solution works, second hunspell do.

>> to produce false positives

I search phrasal verb with maximum length
"pulled him a face" -->
   1)  test findArticles( "pull him a face"
   2)  test findArticles( "pull a face"  --> in dictionary
   3)  test findArticles( "pull face"
   4)  test findArticles( "pull"


>> Do you still want to work on your alternative solution?

   It means:
   step 1) relocate my algorithm from stardict.cc to dedicated file,
   step 2)
      or a) call my algorithm from articlemaker.cc.
      or b) improve Hunspell integration with my algorithm
I dont understand Hunspell well to chose. Perhaps, "improve Hunspell
integration with my algorithm".

If I will do, I do in new fork, and after make pull request.
Now I have not need to refactor. I have only stardict dictionaries.

My algorithm located in
https://github.com/PavelPoroskov/goldendict/blob/stardict-from-en-search-alts/stardict.cc
,
between "//( begin: search alternatives" and "//) end: search alternatives".

**Pull request closed without merging**
